name: Deploy to Production

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  # ==============================================
  # CODE QUALITY & TESTING
  # ==============================================
  test:
    name: Code Quality & Tests
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath, pdo, sqlite, pdo_sqlite
          coverage: none
          
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        
      - name: Prepare Laravel storage directories
        run: |
          # Ensure all required storage directories exist
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/framework/testing
          mkdir -p storage/logs
          mkdir -p bootstrap/cache

          # Set proper permissions
          chmod -R 775 storage bootstrap/cache

          echo "✓ Storage directories created and permissions set"

      - name: Copy .env file for testing
        run: |
          # Use .env.testing if it exists, otherwise use .env.example
          if [ -f .env.testing ]; then
            cp .env.testing .env
            echo "✓ Using .env.testing configuration"
          else
            cp .env.example .env
            echo "✓ Using .env.example configuration"
          fi

      - name: Generate application key
        run: php artisan key:generate

      - name: Create SQLite database
        run: |
          # Create database file if not using in-memory database
          if ! grep -q "DB_DATABASE=:memory:" .env; then
            touch database/database.sqlite
            echo "✓ SQLite database file created"
          else
            echo "✓ Using in-memory SQLite database"
          fi

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Prepare application for testing
        run: |
          # Clear and rebuild caches
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear

          # Optimize for testing
          php artisan config:cache
          php artisan route:cache

          echo "✓ Application prepared for testing"

      - name: Run PHPStan static analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=1G --no-progress
        
      - name: Run Laravel Pint code style check
        run: ./vendor/bin/pint --test
        
      - name: Run PHP Insights quality check
        run: php artisan insights --no-interaction --min-quality=90 --min-complexity=75 --min-architecture=90 --min-style=90
        continue-on-error: true
        
      - name: Run PHPUnit tests
        run: php artisan test
        continue-on-error: true

  # ==============================================
  # BUILD FRONTEND ASSETS
  # ==============================================
  build:
    name: Build Frontend Assets
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build frontend assets
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: public/build
          retention-days: 1

  # ==============================================
  # DEPLOY TO PRODUCTION
  # ==============================================
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    needs: [test, build]
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, bcmath
          coverage: none
          
      - name: Install Composer dependencies (including Deployer)
        run: |
          # Install all dependencies including dev dependencies for deployment tools
          # Deployer is in require-dev but needed for deployment
          composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist

          # Verify Deployer is installed
          if [ -f vendor/bin/dep ]; then
            echo "✓ Deployer installed successfully"
            vendor/bin/dep --version
          else
            echo "❌ Deployer not found!"
            exit 1
          fi
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-assets
          path: public/build
          
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add server to known hosts with better error handling
          echo "Adding server to known hosts..."

          # Try ssh-keyscan with timeout and retry
          for i in {1..3}; do
            echo "Attempt $i of 3..."
            if ssh-keyscan -H -T 10 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts 2>/dev/null; then
              echo "✓ Successfully added server to known hosts"
              break
            else
              echo "⚠ ssh-keyscan attempt $i failed"
              if [ $i -eq 3 ]; then
                echo "❌ Failed to add server to known hosts after 3 attempts"
                echo "This may cause SSH connection issues, but deployment will continue..."
                # Don't fail the workflow - let SSH handle it with StrictHostKeyChecking
              fi
              sleep 2
            fi
          done

          # Set proper permissions
          chmod 644 ~/.ssh/known_hosts

          # Verify SSH configuration
          echo "SSH configuration:"
          ls -la ~/.ssh/

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection to server..."
          echo "Server: ${{ secrets.SERVER_HOST }}"
          echo "User: jobins-rji"
          echo ""

          # Test SSH connection with detailed output
          if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -v jobins-rji@${{ secrets.SERVER_HOST }} "echo '✓ SSH connection successful'" 2>&1 | tee /tmp/ssh-test.log; then
            echo ""
            echo "✅ SSH connection test PASSED"
          else
            echo ""
            echo "❌ SSH connection test FAILED"
            echo ""
            echo "Possible reasons:"
            echo "1. Server is on a private network (10.10.0.110 suggests private IP)"
            echo "2. Firewall blocking GitHub Actions IP ranges"
            echo "3. SSH_PRIVATE_KEY secret is incorrect"
            echo "4. SERVER_HOST secret is incorrect"
            echo ""
            echo "If your server is on a private network, you have two options:"
            echo "A) Use a self-hosted GitHub Actions runner on the same network"
            echo "B) Use a jump host/bastion server accessible from the internet"
            echo ""
            echo "⚠ Deployment will likely fail if SSH cannot connect"
            echo ""

            # Check if it's a private IP
            if [[ "${{ secrets.SERVER_HOST }}" =~ ^10\. ]] || [[ "${{ secrets.SERVER_HOST }}" =~ ^192\.168\. ]] || [[ "${{ secrets.SERVER_HOST }}" =~ ^172\.(1[6-9]|2[0-9]|3[0-1])\. ]]; then
              echo "🔍 DETECTED: Server IP appears to be a private network address"
              echo "   GitHub Actions runners cannot reach private IPs directly"
              echo ""
              echo "SOLUTION: Set up a self-hosted runner or use a public IP/jump host"
              exit 1
            fi
          fi
          
      - name: Deploy with Deployer
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: |
          # Configure SSH options for Deployer
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

          echo "Starting deployment to ${{ github.event.inputs.environment || 'production' }}..."
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"

          vendor/bin/dep deploy ${{ github.event.inputs.environment || 'production' }} \
            --revision="${{ github.sha }}" \
            --branch="${{ github.ref_name }}" \
            -vvv
            
      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Deployment to ${{ github.event.inputs.environment || 'production' }} completed successfully!"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          
      - name: Deployment failed notification
        if: failure()
        run: |
          echo "❌ Deployment to ${{ github.event.inputs.environment || 'production' }} failed!"
          echo "Please check the logs and consider rolling back."

  # ==============================================
  # POST-DEPLOYMENT VERIFICATION
  # ==============================================
  verify:
    name: Post-Deployment Verification
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Health check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.APP_URL }}/up)
          if [ "$response" != "200" ]; then
            echo "❌ Health check failed with status code: $response"
            exit 1
          else
            echo "✅ Health check passed"
          fi
          
      - name: Verify deployment
        run: |
          echo "✅ Deployment verified successfully!"
          echo "Application URL: ${{ secrets.APP_URL }}"

